export const upcoming = {
	dates: {
		maximum: '2026-03-25',
		minimum: '2026-03-04',
	},
	page: 1,
	results: [
		{
			adult: false,
			backdrop_path: '/6YjnTRBz704LF1uJ3ZC4wsS9T8r.jpg',
			genre_ids: [28, 80, 53],
			id: 1290821,
			original_language: 'en',
			original_title: 'Shelter',
			overview:
				'A man living in self-imposed exile on a remote island rescues a young girl from a violent storm, setting off a chain of events that forces him out of seclusion to protect her from enemies tied to his past.',
			popularity: 511.2021,
			poster_path: '/buPFnHZ3xQy6vZEHxbHgL1Pc6CR.jpg',
			release_date: '2026-01-28',
			title: 'Shelter',
			video: false,
			vote_average: 6.73,
			vote_count: 189,
		},
		{
			adult: false,
			backdrop_path: '/hz7TdCrpLLt2Dz7S3PS2HG9rpAO.jpg',
			genre_ids: [27, 9648, 80],
			id: 1159559,
			original_language: 'en',
			original_title: 'Scream 7',
			overview:
				'When a new Ghostface killer emerges in the quiet town where Sidney Prescott has built a new life, her darkest fears are realized as her daughter becomes the next target. Determined to protect her family, Sidney must face the horrors of her past to put an end to the bloodshed once and for all.',
			popularity: 231.4379,
			poster_path: '/jjyuk0edLiW8vOSnlfwWCCLpbh5.jpg',
			release_date: '2026-02-25',
			title: 'Scream 7',
			video: false,
			vote_average: 6,
			vote_count: 182,
		},
		{
			adult: false,
			backdrop_path: '/vOV4Qy3g791OTzEndiSGoJwuI2M.jpg',
			genre_ids: [53, 28, 12, 18, 14],
			id: 1401778,
			original_language: 'en',
			original_title: 'Turbulence',
			overview:
				'Young married couple Zach and Emmy decide to take a hot air balloon trip across the Italian Dolomites to rekindle their relationship. When they and pilot Harry are joined by a third passenger, Julia, events unfold in ways they could never imagine five thousand meters in the air.',
			popularity: 212.9034,
			poster_path: '/jRuiKL4S9UpLma2ZlM47xIu2gbe.jpg',
			release_date: '2025-11-26',
			title: 'Turbulence',
			video: false,
			vote_average: 5.6,
			vote_count: 54,
		},
		{
			adult: false,
			backdrop_path: '/OO75q1cTWWXDmy52bB79yzpxBt.jpg',
			genre_ids: [53, 878, 80, 28],
			id: 1266798,
			original_language: 'fr',
			original_title: 'Chien 51',
			overview:
				'In the near future, Paris is divided into three zones that separate social classes, and no one can escape ALMA, a predictive AI that has revolutionized law enforcement. When ALMA’s creator is assassinated, Salia, a top agent, and Zem, a jaded cop, are forced to work together to solve a murder that may expose the dark secrets of the system they serve.',
			popularity: 176.5445,
			poster_path: '/olMvhbCRuhTbf6EMKxKGHi2on3L.jpg',
			release_date: '2025-10-15',
			title: 'Dog 51',
			video: false,
			vote_average: 6.3,
			vote_count: 207,
		},
		{
			adult: false,
			backdrop_path: '/u9jE0R1nvkmdWu3bt7Op8joPywa.jpg',
			genre_ids: [12, 53, 878],
			id: 840464,
			original_language: 'en',
			original_title: 'Greenland 2: Migration',
			overview:
				'Having found the safety of the Greenland bunker after the comet Clarke decimated the Earth, the Garrity family must now risk everything to embark on a perilous journey across the wasteland of Europe to find a new home.',
			popularity: 119.2106,
			poster_path: '/z2tqCJLsw6uEJ8nJV8BsQXGa3dr.jpg',
			release_date: '2026-01-07',
			title: 'Greenland 2: Migration',
			video: false,
			vote_average: 6.507,
			vote_count: 539,
		},
		{
			adult: false,
			backdrop_path: '/z4hZZQ1GRuNGdeeWfKZIt8PXrmX.jpg',
			genre_ids: [28],
			id: 1244975,
			original_language: 'fr',
			original_title: 'Les Orphelins',
			overview:
				"Gab and Driss, childhood friends on bad terms since they left the orphanage, now have opposite lives - one is a cop with the IGPN, the other a fixer for thugs. When their first love dies in a suspicious accident, her 17-year-old daughter, Leïla, takes Gab's gun and sets off on the trail of a powerful organization willing to do anything to cover the case up. Forced to team up, the orphans must stop her before she crosses a line she can't return from...",
			popularity: 95.7573,
			poster_path: '/hP7mjZr2SVfjAorlRHTdV1XZmHY.jpg',
			release_date: '2025-08-20',
			title: 'The Orphans',
			video: false,
			vote_average: 6.153,
			vote_count: 62,
		},
		{
			adult: false,
			backdrop_path: '/jFKbhV0uFZuA3K73UJIq1dzisCi.jpg',
			genre_ids: [16, 878, 12, 14, 10751],
			id: 804370,
			original_language: 'fr',
			original_title: 'Arco',
			overview:
				'10-year-old Arco lives in a far future. During his first flight in his rainbow suit, he loses control and falls into the past. Iris, a girl his age from 2075, comes to his rescue and tries by all means to help send him back to his era.',
			popularity: 102.8511,
			poster_path: '/ipE3XiHqbSQm3HS0tJ09CDaJ2Fs.jpg',
			release_date: '2025-10-22',
			title: 'Arco',
			video: false,
			vote_average: 7.622,
			vote_count: 94,
		},
		{
			adult: false,
			backdrop_path: '/vSQSYd2zZTqc0zmHImwWEGGluMI.jpg',
			genre_ids: [10749, 18],
			id: 1316092,
			original_language: 'en',
			original_title: '"Wuthering Heights"',
			overview:
				'Tragedy strikes when Heathcliff falls in love with Catherine Earnshaw, a woman from a wealthy family in 18th-century England.',
			popularity: 79.5161,
			poster_path: '/ywRO5dyE8RyyXJd6cvd69jLZeic.jpg',
			release_date: '2026-02-11',
			title: '"Wuthering Heights"',
			video: false,
			vote_average: 6.484,
			vote_count: 430,
		},
		{
			adult: false,
			backdrop_path: '/1qwhYqg7YEZajh3Q4biqbuQoDq8.jpg',
			genre_ids: [16, 35, 10751, 28],
			id: 1297842,
			original_language: 'en',
			original_title: 'GOAT',
			overview:
				'A small goat with big dreams gets a once-in-a-lifetime shot to join the pros and play roarball, a high-intensity, co-ed, full-contact sport dominated by the fastest, fiercest animals in the world.',
			popularity: 67.267,
			poster_path: '/wfuqMlaExcoYiUEvKfVpUTt1v4u.jpg',
			release_date: '2026-02-11',
			title: 'GOAT',
			video: false,
			vote_average: 7.5,
			vote_count: 85,
		},
		{
			adult: false,
			backdrop_path: '/fAF3VGFBpItWNROmiGob60n0y5.jpg',
			genre_ids: [27],
			id: 1242937,
			original_language: 'en',
			original_title: 'The Dreadful',
			overview:
				"In medieval England, Anne and her domineering mother-in-law Morwen struggle to survive on the outskirts of society. But when a man from Anne's past returns from war, a curse begins to take shape through a mysterious knight and threatens to destroy them all.",
			popularity: 53.7243,
			poster_path: '/hGH8Ji7pG2ytHxo7ABqHM3TpzFA.jpg',
			release_date: '2026-02-20',
			title: 'The Dreadful',
			video: false,
			vote_average: 6.5,
			vote_count: 47,
		},
		{
			adult: false,
			backdrop_path: '/cYyNJzwhaj7aC4uTlUctrfaERbf.jpg',
			genre_ids: [28, 18, 36],
			id: 1305781,
			original_language: 'zh',
			original_title: '镖人：风起大漠',
			overview:
				'Dao Ma, the "second most wanted fugitive," is entrusted by his benefactor, the chief of Mo family clan, to take on a mysterious escort mission-escorting the "most wanted fugitive" to Chang\'an.',
			popularity: 53.6055,
			poster_path: '/AbunjMKX4P1sDNlKfhYrWkIoRD9.jpg',
			release_date: '2026-02-17',
			title: 'Blades of the Guardians: Wind Rises in the Desert',
			video: false,
			vote_average: 7.727,
			vote_count: 22,
		},
		{
			adult: false,
			backdrop_path: '/qKWDHofjMHPSEOTLaixkC9ZmjTT.jpg',
			genre_ids: [18],
			id: 1317288,
			original_language: 'en',
			original_title: 'Marty Supreme',
			overview:
				'Marty Mauser, a young man with a dream no one respects, goes to hell and back in pursuit of greatness.',
			popularity: 60.2578,
			poster_path: '/lYWEXbQgRTR4ZQleSXAgRbxAjvq.jpg',
			release_date: '2025-12-19',
			title: 'Marty Supreme',
			video: false,
			vote_average: 7.525,
			vote_count: 1080,
		},
		{
			adult: false,
			backdrop_path: '/2RrLuIfIzGWWIH8IAEo6o0IYHmx.jpg',
			genre_ids: [16, 10751, 35, 878],
			id: 1327819,
			original_language: 'en',
			original_title: 'Hoppers',
			overview:
				"Scientists have discovered how to 'hop' human consciousness into lifelike robotic animals, allowing people to communicate with animals as animals. Animal lover Mabel seizes an opportunity to use the technology, uncovering mysteries within the animal world beyond anything she could have imagined.",
			popularity: 59.7307,
			poster_path: '/d7WizU73PscO3dQor0Ogfx9xy8N.jpg',
			release_date: '2026-02-28',
			title: 'Hoppers',
			video: false,
			vote_average: 8.1,
			vote_count: 18,
		},
		{
			adult: false,
			backdrop_path: '/73BClq9FOcrWrutnpiqhCNEWEwJ.jpg',
			genre_ids: [18, 10749, 36],
			id: 858024,
			original_language: 'en',
			original_title: 'Hamnet',
			overview:
				"The powerful story of love and loss that inspired the creation of Shakespeare's timeless masterpiece, Hamlet.",
			popularity: 59.5105,
			poster_path: '/vbeyOZm2bvBXcbgPD3v6o94epPX.jpg',
			release_date: '2025-11-26',
			title: 'Hamnet',
			video: false,
			vote_average: 7.7,
			vote_count: 808,
		},
		{
			adult: false,
			backdrop_path: '/oN4TQ1TxchynXlFiXFBL3NHLT54.jpg',
			genre_ids: [16, 10751, 18],
			id: 1167307,
			original_language: 'en',
			original_title: 'David',
			overview:
				'From the songs of his mother’s heart to the whispers of a faithful God, David’s story begins in quiet devotion. When the giant Goliath rises to terrorize a nation, a young shepherd armed with only a sling, a few stones, and unshakable faith steps forward. Pursued by power and driven by purpose, his journey tests the limits of loyalty, love, and courage—culminating in a battle not just for a crown, but for the soul of a kingdom.',
			popularity: 47.5298,
			poster_path: '/7lFG1WrCwAxBfyGK8ahlBVzXno7.jpg',
			release_date: '2025-12-14',
			title: 'David',
			video: false,
			vote_average: 8.1,
			vote_count: 94,
		},
		{
			adult: false,
			backdrop_path: '/xcBlMEvzuaHoWANKYn5PGvcW4OC.jpg',
			genre_ids: [27, 28, 53],
			id: 1110034,
			original_language: 'no',
			original_title: 'Kraken',
			overview:
				'Marine biologist Johanne is doing research on a fish farm in Vangsnes, a rural community located by the fjord, when she encounters several strange occurrences. Along with the brutal deaths of two local teenagers, all signs point to the deep fjord; can there be more to the depths than the eye can see? At the bottom of the deepest fjord rests a mythical monster as large as a mountain, with a myriad of arms ready to crush and devour anything they can grab.',
			popularity: 44.4099,
			poster_path: '/jVsflOu9WpMqUJ3WwVX2mITi86S.jpg',
			release_date: '2026-02-06',
			title: 'Kraken',
			video: false,
			vote_average: 7.667,
			vote_count: 6,
		},
		{
			adult: false,
			backdrop_path: '/yWZc7ZglTAecVLKHS0oROuetKce.jpg',
			genre_ids: [80, 53],
			id: 1171145,
			original_language: 'en',
			original_title: 'Crime 101',
			overview:
				'When an elusive thief whose high-stakes heists unfold along the iconic 101 freeway in Los Angeles eyes the score of a lifetime, with hopes of this being his final job, his path collides with a disillusioned insurance broker who is facing her own crossroads. Determined to crack the case, a relentless detective closes in on the operation, raising the stakes even higher.',
			popularity: 43.0818,
			poster_path: '/2HoR2x23bqKpopluoBD1FH3tBi7.jpg',
			release_date: '2026-02-11',
			title: 'Crime 101',
			video: false,
			vote_average: 6.991,
			vote_count: 117,
		},
		{
			adult: false,
			backdrop_path: '/jt2CY2fZeeGAMnc2iQgutBfudS.jpg',
			genre_ids: [18, 878, 14],
			id: 878608,
			original_language: 'zh',
			original_title: '狂野时代',
			overview:
				'In a future where humanity has surrendered its ability to dream in exchange for immortality, an outcast finds illusion, nightmarish visions, and beauty in an intoxicating world of his own making.',
			popularity: 42.5656,
			poster_path: '/wBXvXc7CoE1TCEL96VzMkMQKYG9.jpg',
			release_date: '2025-11-22',
			title: 'Resurrection',
			video: false,
			vote_average: 6.674,
			vote_count: 43,
		},
		{
			adult: false,
			backdrop_path: '/8XeUEIXiZiRNqz0EcKC65vje8Th.jpg',
			genre_ids: [878, 27, 35],
			id: 1159831,
			original_language: 'en',
			original_title: 'The Bride!',
			overview:
				'A lonely Frankenstein travels to 1930s Chicago to ask groundbreaking scientist Dr. Euphronious to create a companion for him. The two revive a murdered young woman and The Bride is born. But what ensues is beyond what either of them imagined.',
			popularity: 38.5798,
			poster_path: '/lV8YHwGkYZsm6EfIqnhaSz2avKt.jpg',
			release_date: '2026-03-04',
			title: 'The Bride!',
			video: false,
			vote_average: 8.5,
			vote_count: 2,
		},
		{
			adult: false,
			backdrop_path: '/lAtuFCx6cYkNBmTMSNnLE0qlCLx.jpg',
			genre_ids: [28, 80, 10749],
			id: 1271895,
			original_language: 'zh',
			original_title: '96分鐘',
			overview:
				'Former bomb disposal expert, Song Kang-Ren, and his fiancée, Huang Xin, board a high-speed train that contains a bomb. At the same time, Liu Kai, a well-known physics teacher who was involved in an affair scandal, also boards this same train in order to win back his wife, Ting Juan, who took the prior high-speed rail to return home in frustration…  After all, can the bomb be successfully defused this time? and resolve the crisis?',
			popularity: 32.903,
			poster_path: '/gWKZ1iLhukvLoh8XY2N4tMvRQ2M.jpg',
			release_date: '2025-09-05',
			title: '96 Minutes',
			video: false,
			vote_average: 5.869,
			vote_count: 65,
		},
	],
	total_pages: 59,
	total_results: 1168,
};
